version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mi_base_datos
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB=mi_base_datos

  frontend:
    build: ./frontend  # o ./frontend/angular si moviste el Dockerfile
    ports:
      - "4200:8080"
    depends_on:
      - backend

volumes:
  mysql_data: